[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = ""
  NEXT_PUBLIC_SUPABASE_ANON_KEY = ""
  NEXT_PUBLIC_SITE_URL = ""

[functions]
  # Передаём переменные в функции
  included_files = [".env"]

[[plugins]]
  package = "@netlify/plugin-nextjs"
